version: 1.2
workflows:
   -  name: cardEndToEndVcfMethyl
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/cardEndToEndVcf.wdl
   -  name: pepperMarginDvWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/pepper_margin_deepvariant.wdl
   -  name: dipdiffWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/dipdiff.wdl
   -  name: snifflesWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/sniffles.wdl
   -  name: minimapWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/minimap.wdl
